add handlers for restapi
Palanti-r/go-rest-api-homework pull request #1
Opened 2023-12-24 14:39 UTC by Palanti-r

added 4 methods

2023-12-24 15:33 UTC, robotomize requested changes
Несколько мелких недостатков, которые нужно исправить, чтобы сдать работу.

Еще один важный момент .gitignore должен быть уровнем выше там где у вас лежит go код. А папку .idea нужно убрать из под контроля версий.  Постарайтесь сделать это в этой работе или взять на будущее на заметку, чтобы лишние файлы не добавлять в репозиторий

2023-12-24 15:33 UTC, robotomize commented on precode.go
> +	if ok != ok {
В данном случае у вас всегда будет истина. Нужно проверить, что ok это true например так
`
if ok {}
`

2023-12-24 15:33 UTC, robotomize commented on precode.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Забыли return после http.Error иначе у вас фактически дальше будет выполнятся код

2023-12-24 15:33 UTC, robotomize commented on precode.go
> +		return
Желательно эту ошибку залогировать через fmt.Println или log.Println

2023-12-25 10:08 UTC, closed without merging

2023-12-25 10:35 UTC, Palanti-r commented
> Несколько мелких недостатков, которые нужно исправить, чтобы сдать работу.
> 
> Еще один важный момент .gitignore должен быть уровнем выше там где у вас лежит go код. А папку .idea нужно убрать из под контроля версий. Постарайтесь сделать это в этой работе или взять на будущее на заметку, чтобы лишние файлы не добавлять в репозиторий

Спасибо большое , постарался все исправить